# Generated by Django 4.2.9 on 2024-02-04 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0003_alter_rating_options'),
        ('ratings', '0003_rating_active_update_timestamp'),
    ]

    operations = [
    ]
